# IMPORTANT for large dataset
* Set the temporary folder to a location where there will be plenty of space  
vtools admin --set_runtime_option 'temp_dir=<folder location with large space>'

# Import  
http://varianttools.sourceforge.net/Vtools/Import  
--var_info


# Custom annotation file  
http://varianttools.sourceforge.net/Annotation/New


# Quick start to vtools  

1. Generate a project called anno  
vtools init anno

2. Project settings  
**IMPORTANT for large dataset**  
Set the temporary folder to a location where there will be plenty of space  
vtools admin --set_runtime_option 'temp_dir=<folder location with large space>'  
  
3. First import the variants  
vtools import /home/data/file.vcf --format vcf --build hg19 --var_info id filter  
  
4. Next import custom annotations in vcf format  

* Generate a custom .ann file (define what annotations you will be importing; See dropbox for an example)  
https://www.dropbox.com/s/vqi6jcfrzj4bwhd/ExAc_r0p3.ann?dl=0  
  Relevant vtools manual: http://varianttools.sourceforge.net/Annotation/New 
  
* Import vcf annotation  
vtools use /data/db_vcf.ann --files /hernandez/netapp/maka/joint/FINAL.2015-10-30/anno/Project_BUR_10518_WGS.2015-12-21/temp_sites/chr22.vcf  

